# Papers

## 1. Electrification as a shock to labour demand: worker skills and internal migration in Sweden

Electricity and the world wide web vie to be crowned the most important general purpose technology (GPT) widely adopted during the 20th century. Both dramatically reshaped the way in which our markets function for consumers and workers, and productivity increases which lagged behind the adoption of the GPTs raised living standards across the globe.

Electricity allowed firms to change their methods of production as it replaced steam power. Electricity acted both as a substitute and a complement for labour within these firms. The extent to which electricity changed the type of labour required by firms has bearing on the imminent adoption of Artificial Intelligence (AI) in the 21st century. Policy makers can better respond to the potential "hollowing-out" of the labour market (a bifurcation whereby high-skilled programmers at the top of the income distribution are vastly outnumbered by low-paid service workers at the bottom of the distribution) if we look back and learn from the past.

The first paper in the thesis will examine the expansion of the electricity network in Sweden, first from private provides and then the national grid, focussing on the shock that this provided to the kinds of skills workers needed to complement this new technology within firms.

Using rich geographic data on the expansion of the electricity network in Sweden, I will assess how firms responded to the new technology as it was adopted. I will use census data to assess internal migration as a response to the new technology.

I will also make use of high frequency data on firm demand for certain skills that could not be met by the recruitment of local workers. The Riksvakanslistan are weekly records of demand for workers by occupation at the county level I plan to digitize.

Questions I would like to answer in this paper include:

1. Did electrification in early-adopter regions incentivise firms to source skilled labour from elsewhere in the country.
2. Did internal migration allow occupational specialization that compounded Marshall Arrow Romer (MAR) externalities, with firms making similar products locating nearby one another and taking advantage of the strong knowledge spillovers that come with localization. 
3. Was it instead upskilling of local workers that allowed Sweden's distinctive development of regionally specialised industries?

## 2. What happens to a dream deferred? The social segregational consequences of the redevelopment of Norrmalm in Stockholm.

<blockquote>

What happens to a dream deferred?

Does it dry up
like a raisin in the sun?
Or fester like a sore—
And then run?
Does it stink like rotten meat?
Or crust and sugar over—
like a syrupy sweet?

Maybe it just sags
like a heavy load.

Or does it *explode*?
      
</blockquote>

[Harlem](https://www.poetryfoundation.org/poems/46548/harlem) -- Langston Hughes



## 3. Movin' Out: The labour market consequences of the redevelopment of Norrmalm in Stockholm.

<iframe width="560" height="315" src="https://www.youtube.com/embed/cJtL8vWNZ4o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

The redevelopment of Norrmalm


## 3. The Long And Winding Road: The mobility consequences of the redevelopment of Norrmalm in Stockholm.

<iframe width="560" height="315" src="https://www.youtube.com/embed/fR4HjTH_fTM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

How do different transportation technologies impact time spent commuting in Stockholm?

