
# Reading notes

## On electricity and technological change

#### WIP from Hillary Vipond (LSE)

Her article [here](https://ehs.org.uk/technological-unemployment-in-victorian-britain/) looks at technological unemployment in Victorian Britain - focussing on English boot making.

She contrasts existing literature - @frey_technology_2019 who is concerned with XXX and Mokyr et al (2015) who is less concerned about the destruction of jobs.

She has two concecntrated questions she wants to answer:

1. were unionized bootmakers better able to retain employment as the indsutry mechanised? 

2. Second, did the trade union provide funds to enable unemployed bootmakers to travel in search of new employment. 

#### Bjorn Brey on electrification in Switzerland

Brey (2021) finds that "locations which were able to adopt electricity early experienced an immediate shift in employment from agriculture into manufacturing. Further, areas that had adopted electricity continued to be more industrialized and have higher incomes over 100 years later."


#### The history of technological anxiety and the future of econoic growth: is this time different? 

Joel Mokyr, Chris Vickers, and Nicholas L. Ziebarth.

Basic point is that people have been concerned about technology replacing human labour and slowing of growth since antinxity and the dawn of modern economic growth respectively.

Three major concerns in history:

1. Widespread substitution of machines for labour - short run increase in inequality is bad, even if long run is better off. 
2. Moral concerns with technoloical progress. People like to find meaning in work - what will it mean if work is replaced?

3. Pessimistic view - technological progress is done mostly, insufficient technological progress and 'headwinds' in the West. 

##### On the anxieties over technology - starting with the trade-off between short term costs and long-term benefits.

David Ricardo changed his opinion on the short-run costs of technological progress - saying that because labour is substituted with machines, this is "often very injurious to the interests of the class of labourers". 33

BUT that in the long run "higher productivity would lead to higher saving and eventually rising demand for labour" 33. 

Adoption of new technology is like a prisoner's dilemma as seen by the 'reactionaries' - if Britain didn't adopt it other nations would and then out compete them.

They cite Vikers and Ziebarth (2012) who show that some of skill biased technological pain caused pain that may have spilled into higher rates of criminal behaviour for those with skills depreciated by mechanization. 

Concerns of the Luddites didn't materialize - why? becase new kinds of work were created and the mechanisation displaced a specific set of jobs. "Technological change increased the demand for other types of labour that were complementary to the capital goods embodied in the new technologies. increase demand for labour included such obvious jobs as mechanics to fx the new machiens, but it extended to jobs for supervisors to oversee the new factory system and accountants to manage enterprieses operatirng on an unprecedented scale" 36. 

"More importantly, technological progress also took the form of product innovation, and thus created entirely new sectors of the economy."

Find ref to Knut Wicksell from 1901 or 1934 who distinguished first between labour saving and labour augmenting technologies.

##### Technology and the alienation of labour

##### Technology and the end of work?

New kinds of technologies have the ability to substittute for more cognitive tasks than before - leads to two problems. First, will humans be pushed out of the labour market such that they earn less and have a lower standard of living. Second, how will they fill their time and 'make a contribution' in the words of Summers - that economists must recognize "the fundamental human satisfactions that comes from making a contribution".

Mokeyr et al. cite some nonsense about how highly educated individuals in the US work more hours per week now than those with a highschool education - who have seen an increase in leisure time in watching TV.

<aside>

Could be interesting to look at the American Time Use survey and see how much time people have substituted from watching TV to looking at your phone etc. I don't really watch TV at all but I spend a long time looking at the internet...

</aside>

Mokeyr et al. say part of the reason for the decline in work hours of the lower-skilled workers is due to less work for them to do - seen in higher unemployment rates for those with just a high school degree.

Maybe it would be possible for people to be pushed further out of work - but still have a high standard of living through low cost leisure activities... then political disruption may be minimal? 

<blockquote>

"Discussions of how technology may affect labour demand are often focused on existing jobs, which can offer insights about which occupations may suffer the greatest dislocation, but offer much less insight about the emergence of as-yet-nonexistent occupations of the future." p 45.

</blocquote>

Greater temporal flexibility is associated with greater gender equality (Goldin 2014 on pharmacists) -- but greater flexibility means firms may have more power over workers - there is a penality for part time work across lots of countries and temp contracts mean highly variable pay for workes - less certainty means it is harder to plan and do domestic finance etc.

##### Disruption!

We are in a positon to provide government support in the coming transition - not like the industrial revolution before. 

<blockquote>

"...there is a distinct possibility that wages for some classes of workers may need to be supplemented through some income redistribution. In addition, it may be necessary to expand the set of publicly provided goods to include certain primary goods such as food, housing, education and health care that are necessary for a modern life to go well." p 47.

</blockquote>

Possibly moving to a world with lots of cheap goods but high levels of wealth inequality. Potentially to reach a place where only those who want to, work. 


#### Demographics and Automation

Daron Acemoglu and Pascual Restrepo (2021)  Restud.

<blockquote>

We argue theoretically and document empirically that aging leads to greater (industrial) automation,
because it creates a shortage of middle-aged workers specializing in manual production tasks. We show
that demographic change is associated with greater adoption of robots and other automation technologies
across countries and with more robotics-related activities across U.S. commuting zones. We also document
more automation innovation in countries undergoing faster aging. Our directed technological change model
predicts that the response of automation technologies to aging should be more pronounced in industries
that rely more on middle-aged workers and those that present greater opportunities for automation and
that productivity should improve and the labor share should decline relatively in industries that are more
amenable to automation. The evidence supports all four of these predictions.

</blockquote>

#### Labour Scarcity, Technology Adoption and Innovation: Evidence from the Cholera Pandemics of 19th C France

Raphael Franck

"...in the short run, a larger share of cholera death in the population had a positive and significant effect on technology adoption and innovation in agriculture, but a negative an significant impact on technology adoption in industry." p3

"As such, our results suggest that labour and capital are substiute factors of production in agriculture and complementary in the industrial sector, in line with recent studies on the impact of labour scarcity that rely on plicy variations in migration." p3. 

Main mechanism is the accumulation of human capital - when there is a labour scarcity the returns to human capital become larger.

#### The Technology Trap

Capital, Labour and Power in the Age of Automation - Carl Benedikt Frey.

<blockquote>

One reason economic growth was stagnant for millenia is that the world was caught in a technology trap, in which labour-replacing technology was consistently and vigorously resisted for fea of its destabilizing force. p. xiii

</blockquote>

- Regarding the replacement of street lamps with electric street lights: "And as so often in history, simplification was merely a step towards automation" p. 2

"... before the late nineteenth century, resistence to technologies that threatened workers skills were the rule rather than the exception". p 9

"The extent to which labour-saving technologies will cause dislocation depents on whether they are enabling or replacing. Replacing technologies render jobs and skills redundant. Enabling technlogies, in contrast, make people more productive in existing tasks or create entirely new jobs for them." p. 13

Examples of labour enabling technologies:

- Computer-aided design software made architects, enginers and other skilled professionals more productive by helping rather than replacing them. 

Acemoglu and Restrepo's framework for examining labour replacement and trade-offs: background for this book.

Both the Industrial and the Computer revolution primarily created jobs for another fellow, whose skills could not have been more different from those of the displaced worker.

** Seems to be a bit of a contrast between the message of Enrico Moretti - who says that agglomeration will save us as high productivity workers raise the wages of those who work in non-tradeable sectors. In contrast, Frey says that automation can cause the same problems for workers in non-tradeable sectors as globalization has for those who lost their jobs to offshoring. ** 

###### A brief history of preindustrial progress

Prior to Neolithic revolution there was no need for private property - agriculture changed that as food surpluses were worth protecting. 


